#!/usr/bin/env bash
set -e

# works for Linux and Darwin

# Config
VERSION=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
GITLEAKS_BIN="${GITLEAKS_BIN:-/usr/local/bin/gitleaks}"
GITLEAKS_CONFIG="${GITLEAKS_CONFIG:-.gitleaks.toml}"


# Detect OS/ARCH
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"
case "$OS" in
    linux) OS_NAME="linux" ;;
    darwin) OS_NAME="darwin" ;;
    *) echo "Unsupported OS"; exit 1 ;;
esac
case "$ARCH" in
    x86_64|amd64) ARCH_NAME="x64" ;;
    arm64|aarch64) ARCH_NAME="arm64" ;;
    *) echo "Unsupported ARCH"; exit 1 ;;
esac

# Install gitleaks if missing
if ! command -v "$GITLEAKS_BIN" >/dev/null 2>&1; then
    echo "gitleaks not found, installing gitleaks version: $VERSION ..."
    URL="https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_${OS_NAME}_${ARCH_NAME}.tar.gz"
    curl -sSL "$URL" | tar -xz --to-stdout gitleaks | sudo tee "$GITLEAKS_BIN" > /dev/null && sudo chmod +x "$GITLEAKS_BIN"
fi

# If gitleaks disabled then enable it
if [ "$(git config --bool gitleaks.enable || echo "true")" != "true" ]; then
  echo "gitleaks pre-commit hook enabling..."
  git config gitleaks.enable true
fi

# Run gitleaks
echo "Running gitleaks pre-commit scan..."

if ! "$GITLEAKS_BIN" protect --staged --config "$GITLEAKS_CONFIG" --redact --no-banner --verbose; then
  echo "-----"
  echo "Commit blocked: secrets detected by gitleaks"
  echo "Remove secrets or disable hook:"
  echo "git config gitleaks.enable false"
  echo "-----"
  exit 1
fi

echo "No secrets detected"
exit 0